name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Tsoa with Express"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: yarn test

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ./build
            ./package.json
            ./yarn.lock

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./Tsoa with Express

      - name: Prepare Deployment Directories
        uses: appleboy/ssh-action@master
        with:
          host: 184.72.205.13 # Server IP address
          username: ${{ secrets.SERVER_USERNAME }} # Server username from secrets
          key: ${{ secrets.SSH_KEY }} # SSH private key from secrets
          port: 22 # SSH port, usually 22
          script: |
            mkdir -p /home/ubuntu/Project/API_Test

      - name: Install Yarn
        uses: appleboy/ssh-action@master
        with:
          host: 184.72.205.13
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y curl
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update && sudo apt install -y yarn

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: 184.72.205.13
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./Tsoa with Express/*"
          target: "/home/ubuntu/Project/API_Test"
          strip_components: 1

      - name: Create .env File
        uses: appleboy/ssh-action@master
        with:
          host: 184.72.205.13
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "NODE_ENV=production" > /home/ubuntu/Project/API_Test/.env
            echo "PORT=your_port_number" >> /home/ubuntu/Project/API_Test/.env
            echo "DATABASE_URL=your_database_url" >> /home/ubuntu/Project/API_Test/.env

      - name: Install Dependencies and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: 184.72.205.13
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Project/API_Test
            yarn install --production
            if pm2 show your-service-name > /dev/null; then
              echo "Application is running. Restarting..."
              pm2 restart your-service-name
            else
              echo "Application is not running. Starting..."
              pm2 start your-service-name
