name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
      working-directory: './Tsoa with Express'

    - name: Install ESLint
      run: yarn add eslint --dev
      working-directory: './Tsoa with Express'

    - name: Generate TSOA routes and spec
      run: yarn tsoa:gen
      working-directory: './Tsoa with Express'

    - name: Run tests
      run: yarn test
      working-directory: './Tsoa with Express'

    - name: Build application
      run: yarn build
      working-directory: './Tsoa with Express'

    - name: Lint code
      run: yarn lint
      working-directory: './Tsoa with Express'
